// @ts-expect-error — generated by `opennextjs-cloudflare build`, absent until then
import handler from "./.open-next/worker.js";

/**
 * Worker entrypoint.
 *
 * The adapter generates `.open-next/worker.js` exporting ONLY `fetch`. Cron
 * needs a `scheduled()` handler, and the adapter has no hook for one, so
 * wrangler's `main` points here instead and this file re-exports the
 * generated fetch untouched.
 *
 * See https://opennext.js.org/cloudflare/howtos/custom-worker
 *
 * WHY scheduled() GOES BACK THROUGH handler.fetch()
 *
 * The obvious implementation — import the sweep function and call it — does
 * not work, and fails silently rather than loudly.
 *
 * The generated worker's fetch is
 * `runWithCloudflareRequestContext(request, env, ctx, ...)`, and that wrapper
 * is what calls `populateProcessEnv()` (copying the Worker `env` into
 * `process.env`) and installs the AsyncLocalStorage that backs
 * `getCloudflareContext()`. Neither happens on the scheduled path, because
 * `scheduled()` is not wrapped. Call the sweep directly and `DATABASE_URL`,
 * `OWNER_ALERT_PHONE`, and the Twilio credentials are all undefined — at
 * which point `isOrdersDbConfigured()` returns false and the route answers
 * `{ok: true, skipped: "no database"}`. A cron that reports success while
 * never alerting is precisely the failure this alert exists to catch.
 *
 * This is NOT the worker fetching its own public URL. `handler.fetch(...)` is
 * a direct in-process function call: no socket, no DNS, no
 * WORKER_SELF_REFERENCE hop. The synthetic Request is just the envelope that
 * carries us through the context wrapper.
 */

/** Must match the route path and the secret the route checks. */
const SWEEP_PATH = "/api/cron/unprinted-alert";

interface CronEnv {
  CRON_SECRET?: string;
}

export default {
  // Unchanged. The generated fetch never references `this`, so passing it
  // through unbound is safe.
  fetch: handler.fetch,

  async scheduled(
    controller: ScheduledController,
    env: CronEnv,
    ctx: ExecutionContext,
  ): Promise<void> {
    // The hostname is arbitrary — nothing resolves it.
    const request = new Request(`https://cron.internal${SWEEP_PATH}`, {
      method: "GET",
      headers: env.CRON_SECRET
        ? { authorization: `Bearer ${env.CRON_SECRET}` }
        : {},
    });

    try {
      const response = await handler.fetch(request, env, ctx);
      if (!response.ok) {
        // Loud. A sweep that 401s or 503s must not look like a quiet success
        // in the Workers dashboard.
        console.error(
          `[cron] ${controller.cron} ${SWEEP_PATH} -> ${response.status}: ` +
            (await response.text()).slice(0, 500),
        );
      }
    } catch (err) {
      console.error(
        `[cron] ${controller.cron} ${SWEEP_PATH} threw:`,
        err instanceof Error ? err.message : String(err),
      );
    }
  },
};
